### ISSUE TITLE
RIL NOT WORKING ON S6312

### ISSUE THREAD

**Issue by sksshivam96** [CyanogenMod-S6310/bugs_report#10]
IF YOU WILL MAKE SUITABLE FILES FOR THE ISSUE ABOVE I AM READY TO FLASH THOSE FILES. THUS, THE ROM WILL BE AVAILABLE FOR S6312 TOO.

**Comment by lesleyxxx12** [comment]
I'm working on it, calm down please.

**Comment by Nothing-Dev** [comment]
WIP, don't ASK for ETA.
