### ISSUE TITLE
My idea fix to camera

### ISSUE THREAD

**Issue by kajvor** [CyanogenMod-S6310/bugs_report#11]
https://play.google.com/store/apps/details?id=com.billgbennett.camerafix&hl=pl&referrer=utm_source%3Dgoogle%26utm_medium%3Dorganic%26utm_term%3Dnie+ma+polaczenia+z+aparatem+cyanogenmod&pcampaignid=APPU_1_0w1bV7K_IKHJ6AT50LeoCw
Download' camera cmfix' and ,camera restart'

I did not help. but I think that is the guiding light :)

**Comment by lesleyxxx12** [comment]
This is not a fix, just a workaround. I want the stock camera app to work.
Can be closed.
