### ISSUE TITLE
Sound output problem

### ISSUE THREAD

**Issue by my24thurs** [CyanogenMod-S6310/bugs_report#3]
Suck as music,notification,game,etc just heard from call speaker/front speaker

**Comment by Nothing-Dev** [comment]
What build are you using?

**Comment by my24thurs** [comment]
Beta 2 cm11

**Comment by Nothing-Dev** [comment]
Mm, okay.

You may only happen to you , in my case is heard from only from the rear, and calls the front

**Comment by Nothing-Dev** [comment]
Correct, you're right.

**Comment by lesleyxxx12** [comment]
Can be closed

**Comment by Nothing-Dev** [comment]
Audio is fixed. Thanks @techyzen101
