### ISSUE TITLE
Force Close Apps

### ISSUE THREAD

**Issue by Malikcx** [CyanogenMod-S6310/bugs_report#4]
Love it But Maybe FixThe fc on some app i have download on plaaystore.. like sorry (paranoid rom) its smooth and no fc on apps.. as i know its build from cm11 source.. sorry for my bad english :)

**Comment by lesleyxxx12** [comment]
I have found out that the most apps are FC'ing because of ads. The ads propably try to use the default rendering engine and that closes the apps. Simply get XPosed with an adblocker for now.

**Comment by Nothing-Dev** [comment]
Try to change the dpi to 140.

**Comment by lesleyxxx12** [comment]
Issue can be closed

**Comment by Nothing-Dev** [comment]
Webview is the fix. Only in my compilations webview are bugged.

Thanks lesleyxxx12
