### ISSUE TITLE
Low Audio

### ISSUE THREAD

**Issue by techyzen101** [CyanogenMod-S6310/bugs_report#6]
Using Build: Beta 2 CM11

I have come across some forums about sound being low on Cyanogenmod releases, not specifically for gt-s6310 but might help.

Seems there's a specific file for each device that has cyanogenmod running on it that needs to be edited
to increases sound:

Samsung Galaxy S III
folder etc\sound
m0 file

<</b>/path</b>>
<</b>device name="speaker"</b>>
<</b>ctl name="Speaker Volume" val= "57" /</b>>
Value was changed to val = "63"

another is:

"etc" folder.
"snd_soc_msm" folder
"snd_soc_msm_2x" file

'RX5 Digital Volume':1:65% -> 'RX5 Digital Volume':1:70%

If there isn't any file from cyanogenmod for royss that is equivalent to these files, then it should be done programmatically then?

**Comment by Nothing-Dev** [comment]
Royss have sound folder un etc?

**Comment by techyzen101** [comment]
Not specifically in a sound folder. I've installed your latest CM release, and been searching for it for quite a while now to no avail. It would be great if we could have some clue of where it might be or IF such file even exists.

**Comment by lesleyxxx12** [comment]
Can be closed
