### ISSUE TITLE
SIM Toolkit Bug

### ISSUE THREAD

**Issue by techyzen101** [CyanogenMod-S6310/bugs_report#7]
Build: Beta 4, cm-11-20160215-UNOFFICIAL-royss
Model: GT-S6310

SIM Toolkit shows two of itself on recent tasks.

![screenshot_2016-02-28-08-57-06](https://cloud.githubusercontent.com/assets/16412733/13377318/bfb717be-de10-11e5-8173-73560d4e5914.png)

**Comment by Nothing-Dev** [comment]
Exactly what is the error ?

**Comment by techyzen101** [comment]
Sorry bout that, added.
