### ISSUE TITLE
problems in the video player and also the lack of various system apps.

### ISSUE THREAD

**Issue by ghost** [CyanogenMod-S6310/bugs_report#9]
Problems in video player that can not play or even a video 240p .mp4 , besides the lack of system apps.

**Comment by lesleyxxx12** [comment]
Bug is OMX related, will try to fix this soon. What lack of system apps?

**Comment by kajvor** [comment]
lack of application ' Google Play'

**Comment by lesleyxxx12** [comment]
To get Google Play you should download GApps from http://opengapps.org/
I am not responsible for the implementation of Google Apps, just for the system.

**Comment by kajvor** [comment]
Platform ,ARM' ?

**Comment by lesleyxxx12** [comment]
Yes

**Comment by kajvor** [comment]
Video fixed to instal mxplayer

**Comment by lesleyxxx12** [comment]
Video is fixed in the general nightly builds
